var name = {
    'ban': '\uf05e',
    'calendar': '\uf073',
    'caret-down': '\uf0d7',
    'camera': '\uf030',
    'check': '\uf00c',
    'close': '\uf00d',
    'cloud-download': '\uf0ed',
    'cog': '\uf013',
    'download': '\uf019',
    'history': "\uf1da",
    'info-circle': "\uf05a",
    'subscript': '\uf12c',
    'tasks': "\uf0ae",
    'times-circle': '\uf057',
    'video-camera': '\uf03d',
    'volume-off': '\uf026',
    'volume-up': '\uf028',
}
